### ISSUE TITLE
Error visible in Portainer when installed

### ISSUE THREAD

**Issue by Maikel-K** [michbeck100/modbus-proxy-docker#1]
Hi,

I really want to use the docker option to run Modbus-proxy as i have been told this will restart automaticly etc.
The original creator seems to not support RPI processors and on the docker hub i found yours.

Im using an RPI 4.

This is my docker-compose.yml file
`tcp_modbus_proxy:
    container_name: modbus-proxy
    image: michbeck100/modbus-proxy:latest
    restart: unless-stopped
    volumes:
      - ./conf.yml:/src/modbus-proxy.yaml
    command: -c /src/modbus-proxy.yaml
    ports:
      - 502:1502
`

It builds and says DONE.

Then in portainer i get this in the error log:

`Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6fdf464 (most recent call first):
<no Python frame>
`

Can you help me checking why it wont run?

**Comment by michbeck100** [comment]
You can mount `./conf.yml` directly to /etc/modbus-proxy.yml, so you don't have to override the command. And you have to flip the network ports. The first entry is the host port on the RPI and the last entry is the port on the container which is 502 for the modbus-proxy. 

This would be the docker-compose.yml:

```yaml
modbus-proxy:
    image: michbeck100/modbus-proxy
    restart: unless-stopped
    container_name: modbus-proxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./conf.yml:/etc/modbus-proxy.yml
    ports:
      - "1502:502"
```

Please try this.

**Comment by Maikel-K** [comment]
i tried that, unfortunatly same error in portainer.
`Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6f84464 (most recent call first):
<no Python frame>`

i was reading online and saw something about running the container as privileged could be needed?

I do see this when building: 

docker-compose up -d
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Creating modbus-proxy ... done


Maybe i need to upgrade some packages too.

**Comment by michbeck100** [comment]
What type of OS are you using on the RPI? And how do you start the docker-compose.yml?

**Comment by Maikel-K** [comment]
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by Maikel-K** [comment]
I do see this when building:

docker-compose up -d
/usr/lib/python3/dist-packages/requests/init.py:91: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Creating modbus-proxy ... done

Maybe i need to upgrade some packages too.

**Comment by michbeck100** [comment]
You can try with 
```yaml
modbus-proxy:
    image: michbeck100/modbus-proxy
    restart: unless-stopped
    container_name: modbus-proxy
    privileged: true
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./conf.yml:/etc/modbus-proxy.yml
    ports:
      - "1502:502"
```

But I don't have to use it. Maybe because the docker runtime already runs as root. 🤔
